name: Update Checksum

on:
  push:
    branches:
      - main

jobs:
  update-checksum:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Calculate new checksum
        working-directory: ./desktop
        id: calc-checksum
        shell: bash
        run: |
          new_checksum=$(openssl dgst -sha512 -binary "dist/release/Shoot Staging Setup 5.0.22.exe" | openssl base64 | awk '{printf "%s", $0}')
          echo "new_checksum=$new_checksum" >> $GITHUB_ENV

      - name: Update checksum in YAML file
        working-directory: ./desktop
        run: |
          sed -i "s#^\(\s*sha512:\s*\).*\$#\1${{ env.new_checksum }}#" dist/release/latest.yml

      - uses: actions/upload-artifact@v4
        with:
          name: latest.yml
          path: desktop/dist/release/latest.yml

      - name: Output the new checksum
        working-directory: ./desktop
        run: |
          echo "New checksum is ${{ env.new_checksum }}"
