name: Update Checksum

on:
  push:
    branches:
      - main

jobs:
  update-checksum:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Calculate new checksum
        working-directory: ./desktop
        id: calc-checksum
        run: |
          new_checksum=$(openssl dgst -sha512 -binary "dist/release/Shoot Staging Setup 5.0.22.exe" | openssl base64)
          echo "new_checksum=$new_checksum" >> $GITHUB_ENV

      - name: Update checksum in YAML file
        working-directory: ./desktop
        run: |
          sed -i "s#^\(\s*sha512:\s*\).*\$#\1${{ env.new_checksum }}#" dist/release/latest.yml

      - name: Output the new checksum
        working-directory: ./desktop
        run: |
          echo "New checksum is ${{ env.new_checksum }}"
